# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f078b26cb9b697fe9a4226dc5cfe6d170b8459467494776bcb9c2bb361c6916def1ffcd3b236219ecc00b38a74c1be82941bfca6286b9bb8d3b5fc87371dfee9

test:
  secret_key_base: 18e5dab385e3a17df28cbec6ce47bf0c39a09337433e2ef71b0fc068dd3341ae8eec96bfb971603bb7b2579e7c71ac7dabbe195e01064b7884950502d6e390bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
